# This file was generated by GoReleaser. DO NOT EDIT.
class Utern < Formula
  desc "Multi group and stream log tailing for AWS CloudWatch Logs"
  homepage "https://github.com/knqyf263/utern"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/knqyf263/utern/releases/download/v0.0.2/utern_0.0.2_darwin_amd64.zip"
    sha256 "8e6da096677aeec09174c3f2a6eb9dd38b4b361f919a199b74a44b56619ba44d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/knqyf263/utern/releases/download/v0.0.2/utern_0.0.2_linux_amd64.zip"
      sha256 "f63e88b64cf477e141d5e5c8363bc421dc56ab57cecc0585613942c440ee2d2e"
    end
  end

  def install
    bin.install Dir['utern']
  end

  test do
    system "#{bin}/utern"
  end
end
