# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Utern < Formula
  desc "Multi group and stream log tailing for AWS CloudWatch Logs"
  homepage "https://github.com/knqyf263/utern"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/knqyf263/utern/releases/download/v0.1.6/utern_0.1.6_darwin_amd64.zip"
      sha256 "36ac3810d93572e16e59eef2aea9611bf8af2d09babc7f7885d4c27f82aa1d85"

      def install
        bin.install Dir['utern']
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/knqyf263/utern/releases/download/v0.1.6/utern_0.1.6_darwin_arm64.zip"
      sha256 "5d0c5060f0f270b13b90a75cea3c72fc1c6d7cc95f3e0e67015050029368f3fb"

      def install
        bin.install Dir['utern']
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/knqyf263/utern/releases/download/v0.1.6/utern_0.1.6_linux_amd64.zip"
      sha256 "6491ecd506bfae227e237cd105e4f27c2a60e4301830f8750d5f4e42ac01173d"

      def install
        bin.install Dir['utern']
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/knqyf263/utern/releases/download/v0.1.6/utern_0.1.6_linux_arm64.zip"
      sha256 "5f0a9bbf4ca811d7679521179db761bbfb3aa20e38afb65143799a75cef4fcec"

      def install
        bin.install Dir['utern']
      end
    end
  end

  test do
    system "#{bin}/utern"
  end
end
